-- MySQL Script generated by MySQL Workbench
-- Do 23 Nov 2017 15:59:59 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema schmitzlabdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema schmitzlabdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `schmitzlabdb` DEFAULT CHARACTER SET utf8 ;
USE `schmitzlabdb` ;

-- -----------------------------------------------------
-- Table `schmitzlabdb`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`Project` (
  `project_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NULL,
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`Animal` (
  `animal_id` INT(11) NOT NULL,
  `project_id` INT UNSIGNED NOT NULL,
  `genotype` VARCHAR(45) NULL,
  `birthdate` DATETIME NULL,
  `sex` ENUM('m', 'f') NULL,
  `name` VARCHAR(45) NULL,
  `pyrat_id` VARCHAR(45) NULL,
  PRIMARY KEY (`animal_id`),
  INDEX `fk_Animal_1_idx` (`project_id` ASC),
  CONSTRAINT `fk_Animal_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `schmitzlabdb`.`Project` (`project_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`Experiment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`Experiment` (
  `experiment_id` INT NOT NULL,
  `project_id` INT UNSIGNED NOT NULL,
  `experimenter` VARCHAR(45) NULL,
  `description` VARCHAR(256) NULL,
  PRIMARY KEY (`experiment_id`),
  INDEX `fk_Experiment_1_idx` (`project_id` ASC),
  CONSTRAINT `fk_Experiment_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `schmitzlabdb`.`Project` (`project_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`Session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`Session` (
  `session_id` INT NOT NULL AUTO_INCREMENT,
  `animal_id` INT(11) NOT NULL,
  `experiment_id` INT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `note` VARCHAR(256) NULL,
  `session_type` ENUM('behav', 'rec', 'both') NULL,
  PRIMARY KEY (`session_id`),
  INDEX `fk_Session_1_idx` (`animal_id` ASC),
  INDEX `fk_Session_2_idx` (`experiment_id` ASC),
  CONSTRAINT `fk_Session_1`
    FOREIGN KEY (`animal_id`)
    REFERENCES `schmitzlabdb`.`Animal` (`animal_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Session_2`
    FOREIGN KEY (`experiment_id`)
    REFERENCES `schmitzlabdb`.`Experiment` (`experiment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`ProbeType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`ProbeType` (
  `probe_type_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`probe_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`Amplifier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`Amplifier` (
  `amplifier_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`amplifier_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`Remapping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`Remapping` (
  `probe_type_id` INT NOT NULL,
  `amplifier_id` INT NOT NULL,
  `probe_channel` INT NULL,
  `connector_channel` INT NULL,
  `headstage_channel` INT NULL,
  INDEX `fk_Remapping_1_idx` (`probe_type_id` ASC),
  INDEX `fk_Remapping_2_idx` (`amplifier_id` ASC),
  CONSTRAINT `fk_Remapping_1`
    FOREIGN KEY (`probe_type_id`)
    REFERENCES `schmitzlabdb`.`ProbeType` (`probe_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Remapping_2`
    FOREIGN KEY (`amplifier_id`)
    REFERENCES `schmitzlabdb`.`Amplifier` (`amplifier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`Probe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`Probe` (
  `probe_id` INT NOT NULL AUTO_INCREMENT,
  `probe_type_id` INT NOT NULL,
  `serialnum` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`probe_id`),
  INDEX `fk_Probe_1_idx` (`probe_type_id` ASC),
  CONSTRAINT `fk_Probe_1`
    FOREIGN KEY (`probe_type_id`)
    REFERENCES `schmitzlabdb`.`ProbeType` (`probe_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`Recording`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`Recording` (
  `rec_id` INT NOT NULL,
  `session_id` INT NOT NULL,
  `probe_id` INT NOT NULL,
  `amplifier_id` INT NOT NULL,
  `depth` DOUBLE NOT NULL,
  `note` VARCHAR(256) NULL,
  PRIMARY KEY (`rec_id`),
  INDEX `fk_Recording_1_idx` (`session_id` ASC),
  INDEX `fk_Recording_3_idx` (`amplifier_id` ASC),
  INDEX `fk_Recording_2_idx` (`probe_id` ASC),
  CONSTRAINT `fk_Recording_1`
    FOREIGN KEY (`session_id`)
    REFERENCES `schmitzlabdb`.`Session` (`session_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Recording_2`
    FOREIGN KEY (`probe_id`)
    REFERENCES `schmitzlabdb`.`Probe` (`probe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recording_3`
    FOREIGN KEY (`amplifier_id`)
    REFERENCES `schmitzlabdb`.`Amplifier` (`amplifier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`Histology`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`Histology` (
  `histology_id` INT NOT NULL AUTO_INCREMENT,
  `rec_id` INT NOT NULL,
  `dye` VARCHAR(45) NOT NULL,
  `staining` VARCHAR(45) NOT NULL,
  `note` VARCHAR(256) NULL,
  INDEX `fk_Histology_1_idx` (`rec_id` ASC),
  PRIMARY KEY (`histology_id`),
  CONSTRAINT `fk_Histology_1`
    FOREIGN KEY (`rec_id`)
    REFERENCES `schmitzlabdb`.`Recording` (`rec_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`Behavior`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`Behavior` (
  `session_id` INT NOT NULL,
  `real_x` DOUBLE NOT NULL,
  `real_y` DOUBLE NOT NULL,
  `virt_x` DOUBLE NOT NULL,
  `virt_y` DOUBLE NOT NULL,
  `time` DOUBLE NOT NULL,
  `virt_end` BINARY(1) NULL DEFAULT 0,
  INDEX `fk_Behavior_1_idx` (`session_id` ASC),
  CONSTRAINT `fk_Behavior_1`
    FOREIGN KEY (`session_id`)
    REFERENCES `schmitzlabdb`.`Session` (`session_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`Anatomy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`Anatomy` (
  `histology_id` INT NOT NULL,
  `score` DOUBLE NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `channel` INT(3) NOT NULL,
  INDEX `fk_Anatomy_1_idx` (`histology_id` ASC),
  CONSTRAINT `fk_Anatomy_1`
    FOREIGN KEY (`histology_id`)
    REFERENCES `schmitzlabdb`.`Histology` (`histology_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`LFP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`LFP` (
  `rec_id` INT NOT NULL,
  `channel` INT(3) NOT NULL,
  `time` DOUBLE NOT NULL,
  `aplitude` DOUBLE NOT NULL,
  INDEX `fk_LFP_1_idx` (`rec_id` ASC),
  CONSTRAINT `fk_LFP_1`
    FOREIGN KEY (`rec_id`)
    REFERENCES `schmitzlabdb`.`Recording` (`rec_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`Juxta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`Juxta` (
  `rec_id` INT NOT NULL,
  `channel` ENUM('rec', 'drive') NOT NULL,
  `time` DOUBLE NOT NULL,
  `amplitude` DOUBLE NOT NULL,
  CONSTRAINT `fk_Juxta_1`
    FOREIGN KEY (`rec_id`)
    REFERENCES `schmitzlabdb`.`Recording` (`rec_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`Patch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`Patch` (
  `rec_id` INT NOT NULL,
  `channel` ENUM('rec', 'drive') NOT NULL,
  `time` DOUBLE NOT NULL,
  `amplitude` DOUBLE NOT NULL,
  INDEX `fk_Patch_1_idx` (`rec_id` ASC),
  CONSTRAINT `fk_Patch_1`
    FOREIGN KEY (`rec_id`)
    REFERENCES `schmitzlabdb`.`Recording` (`rec_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`Shank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`Shank` (
  `shank_id` INT NOT NULL AUTO_INCREMENT,
  `probe_id` INT NOT NULL,
  `num_sites` INT NULL,
  PRIMARY KEY (`shank_id`),
  INDEX `fk_Shank_1_idx` (`probe_id` ASC),
  CONSTRAINT `fk_Shank_1`
    FOREIGN KEY (`probe_id`)
    REFERENCES `schmitzlabdb`.`Probe` (`probe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`OptoStim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`OptoStim` (
  `rec_id` INT NOT NULL,
  `time` DOUBLE NOT NULL,
  `wavelength` DOUBLE NOT NULL,
  `shank_id` INT NULL,
  INDEX `fk_OptoStim_1_idx` (`rec_id` ASC),
  INDEX `fk_OptoStim_2_idx` (`shank_id` ASC),
  CONSTRAINT `fk_OptoStim_1`
    FOREIGN KEY (`rec_id`)
    REFERENCES `schmitzlabdb`.`Recording` (`rec_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_OptoStim_2`
    FOREIGN KEY (`shank_id`)
    REFERENCES `schmitzlabdb`.`Shank` (`shank_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`ElectroStim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`ElectroStim` (
  `rec_id` INT NOT NULL,
  `time` DOUBLE NOT NULL,
  `voltage` DOUBLE NOT NULL,
  INDEX `fk_ElectroStim_1_idx` (`rec_id` ASC),
  CONSTRAINT `fk_ElectroStim_1`
    FOREIGN KEY (`rec_id`)
    REFERENCES `schmitzlabdb`.`Recording` (`rec_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`RewardType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`RewardType` (
  `reward_type_id` INT NOT NULL AUTO_INCREMENT,
  `reward_type` ENUM('positive', 'negative', 'neural') NOT NULL,
  `note` VARCHAR(256) NULL,
  PRIMARY KEY (`reward_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`Reward`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`Reward` (
  `session_id` INT NOT NULL,
  `reward_type_id` INT NOT NULL,
  `time` DOUBLE NOT NULL,
  INDEX `fk_Reward_1_idx` (`session_id` ASC),
  INDEX `fk_Reward_2_idx` (`reward_type_id` ASC),
  CONSTRAINT `fk_Reward_1`
    FOREIGN KEY (`session_id`)
    REFERENCES `schmitzlabdb`.`Session` (`session_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Reward_2`
    FOREIGN KEY (`reward_type_id`)
    REFERENCES `schmitzlabdb`.`RewardType` (`reward_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`StereotacticInjection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`StereotacticInjection` (
  `animal_id` INT NOT NULL,
  `virus_name` VARCHAR(256) NULL,
  `x_coord` DOUBLE NULL,
  `y_coord` DOUBLE NULL,
  `date` DATETIME NULL,
  `volume` DOUBLE NULL,
  `target` VARCHAR(45) NULL,
  INDEX `fk_StereotacticInjection_1_idx` (`animal_id` ASC),
  CONSTRAINT `fk_StereotacticInjection_1`
    FOREIGN KEY (`animal_id`)
    REFERENCES `schmitzlabdb`.`Animal` (`animal_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`DrugInjection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`DrugInjection` (
  `rec_id` INT NOT NULL,
  `drug` VARCHAR(256) NOT NULL,
  `time` DATETIME NOT NULL,
  `volume` DOUBLE NULL,
  `type` ENUM('IP', 'IC', 'SC', 'IM') NULL,
  INDEX `fk_DrugInjection_1_idx` (`rec_id` ASC),
  CONSTRAINT `fk_DrugInjection_1`
    FOREIGN KEY (`rec_id`)
    REFERENCES `schmitzlabdb`.`Recording` (`rec_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmitzlabdb`.`SitePosition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmitzlabdb`.`SitePosition` (
  `shank_id` INT NOT NULL,
  `x_pos` INT UNSIGNED NOT NULL,
  `y_pos` INT UNSIGNED NOT NULL,
  `site_num` INT NOT NULL,
  INDEX `fk_SitePosition_1_idx` (`shank_id` ASC),
  CONSTRAINT `fk_SitePosition_1`
    FOREIGN KEY (`shank_id`)
    REFERENCES `schmitzlabdb`.`Shank` (`shank_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
